- name: Instalar Prometheus e Grafana
  hosts: azure_vms
  become: true
  tasks:
    - name: Criar diretório para Prometheus
      file:
        path: /opt/prometheus
        state: directory
        mode: '0755'

    - name: Criar diretório para Grafana  
      file:
        path: /opt/grafana
        state: directory
        mode: '0755'
        owner: 472
        group: 472

    - name: Garantir permissões corretas para diretórios do Grafana
      file:
        path: /opt/grafana
        state: directory
        mode: '0775'
        owner: 472
        group: 472
        recurse: yes

    - name: Criar diretório para cAdvisor
      file:
        path: /opt/cadvisor
        state: directory
        mode: '0755'

    - name: Criar rede Docker para monitoramento
      docker_network:
        name: monitoring-network
        state: present
    
    - name: Copiar configuração do Prometheus
      copy:
        src: files/prometheus.yml
        dest: /opt/prometheus/prometheus.yml

    - name: Baixar e executar Prometheus, Grafana e cAdvisor com Docker
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        restart_policy: always
        ports: "{{ item.ports }}"
        volumes: "{{ item.volumes | default([]) }}"
        networks:
          - name: monitoring-network
        user: "{{ item.user | default(omit) }}"
      loop:
        - name: prometheus
          image: prom/prometheus
          ports: ["9090:9090"]
          volumes: ["/opt/prometheus:/etc/prometheus"]
        - name: grafana
          image: grafana/grafana
          ports: ["3000:3000"]
          volumes: ["/opt/grafana:/var/lib/grafana"]
          user: "472:472"
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:latest
          ports: ["8080:8080"]
          volumes: 
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker:/var/lib/docker:ro"
